export const MARKER_TEXT = 'generated by driftgate; edit .driftgate/ instead';
export const HTML_MARKER = `<!-- ${MARKER_TEXT} -->`;
export const HASH_MARKER = `# ${MARKER_TEXT}`;

/**
 * The marker is how a human — and `check` — can tell a generated file from a
 * hand-written one at a glance. It goes first wherever the format allows a leading
 * comment; formats that demand other content first (Cursor's `.mdc`, whose frontmatter
 * must be the first bytes) place it immediately after that content instead.
 */
export function withHtmlMarker(body: string, enabled = true): string {
  return enabled ? `${HTML_MARKER}\n\n${body}` : body;
}

export function withHashMarker(body: string, enabled = true): string {
  return enabled ? `${HASH_MARKER}\n\n${body}` : body;
}

/** True when a file's opening bytes claim Driftgate generated it. */
export function hasMarker(contents: string): boolean {
  return contents.slice(0, 512).includes(MARKER_TEXT);
}
