import { describe, expect, it } from 'vitest';
import { ALL_TOOLS, type Canonical } from '@rulegate/adapter-kit';
import { gemini, GEMINI_MD } from '../src/index.js';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';

describe('gemini write()', () => {
  it('matches the golden fixture byte for byte', async () => {
    await expectFixtureMatch('gemini', gemini);
  });

  it('excludes rules that target other tools', async () => {
    const actual = await renderFixture('gemini', gemini);
    expect(actual.get(GEMINI_MD)).not.toContain('This rule must not reach gemini');
  });

  it('records which rules produced the file', async () => {
    const ctx = await contextFor('gemini/input', gemini);
    const [artifact] = await gemini.write(ctx);

    expect(artifact?.provenance?.ruleIds).toEqual(['10-style', '20-testing', '30-frontend']);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent('gemini', gemini);
  });

  it('emits no file when no rule targets this tool', async () => {
    const ctx = await contextFor('gemini/input', gemini);
    const canonical: Canonical = { ...ctx.canonical, rules: [] };
    expect(await gemini.write({ ...ctx, canonical })).toEqual([]);
  });

  it('omits the marker when the manifest disables it', async () => {
    const ctx = await contextFor('gemini/input', gemini);
    const canonical: Canonical = {
      ...ctx.canonical,
      manifest: {
        ...ctx.canonical.manifest,
        options: { ...ctx.canonical.manifest.options, marker: false },
      },
    };
    const [artifact] = await gemini.write({ ...ctx, canonical });
    expect(artifact?.contents.startsWith('## Style')).toBe(true);
  });

  it('keeps the canonical rule order regardless of how rules arrive', async () => {
    const ctx = await contextFor('gemini/input', gemini);
    const reversed: Canonical = { ...ctx.canonical, rules: [...ctx.canonical.rules].reverse() };
    const [a] = await gemini.write(ctx);
    const [b] = await gemini.write({ ...ctx, canonical: reversed });

    expect(b?.contents).toBe(a?.contents);
  });

  it('states a glob-scoped rule in prose, since Gemini has no per-glob mechanism', async () => {
    const ctx = await contextFor('gemini/input', gemini);
    const [artifact] = await gemini.write(ctx);
    expect(artifact?.contents).toContain('**Applies to:** `src/components/**/*.tsx`');
  });

  it('renders a repo-wide rule with no Applies-to line', async () => {
    const ctx = await contextFor('gemini/input', gemini);
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [
        {
          id: 'plain',
          path: '.rulegate/rules/plain.md',
          body: 'Body.\n',
          frontmatter: { globs: [], tools: ALL_TOOLS, order: 100, unknown: {} },
          source: { file: '.rulegate/rules/plain.md' },
        },
      ],
    };
    const [artifact] = await gemini.write({ ...ctx, canonical });
    expect(artifact?.contents).toBe(
      // No `## plain` heading: a rule with no description gets none, rather than one
      // invented from its id. See `renderRuleSection`.
      '<!-- generated by rulegate; edit .rulegate/ instead -->\n\nBody.\n',
    );
  });
});
