import { describe, expect, it } from 'vitest';
import {
  ALL_TOOLS,
  isRulegateError,
  type Canonical,
  type RuleDocument,
} from '@rulegate/adapter-kit';
import { copilot, INSTRUCTIONS_DIR, REPO_INSTRUCTIONS } from '../src/index.js';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';

const FRONTEND_INSTRUCTIONS = `${INSTRUCTIONS_DIR}/30-frontend.instructions.md`;

function rule(over: Partial<RuleDocument> & { id: string }): RuleDocument {
  return {
    path: `.rulegate/rules/${over.id}.md`,
    body: 'Body.\n',
    frontmatter: { globs: [], tools: ALL_TOOLS, order: 100, unknown: {} },
    source: { file: `.rulegate/rules/${over.id}.md` },
    ...over,
  };
}

describe('copilot write()', () => {
  it('matches the golden fixtures byte for byte', async () => {
    await expectFixtureMatch('copilot', copilot);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent('copilot', copilot);
  });

  it('splits rules across the two mechanisms by scope', async () => {
    const actual = await renderFixture('copilot', copilot);

    // Each rule lands in exactly one file. Copilot applies both when they match, so a rule
    // written to both would reach the model twice.
    expect([...actual.keys()].sort()).toEqual([REPO_INSTRUCTIONS, FRONTEND_INSTRUCTIONS]);
    expect(actual.get(REPO_INSTRUCTIONS)).toContain('## Style');
    expect(actual.get(REPO_INSTRUCTIONS)).not.toContain('Prefer server components');
    expect(actual.get(FRONTEND_INSTRUCTIONS)).toContain('Prefer server components');
  });

  it('states the glob in applyTo rather than in prose', async () => {
    const actual = await renderFixture('copilot', copilot);

    // The one MVP tool with a native per-path mechanism, so the scope survives instead of
    // degrading to an "Applies to:" sentence the way it must for Claude Code and Codex.
    expect(actual.get(FRONTEND_INSTRUCTIONS)).toContain("applyTo: 'src/components/**/*.tsx'");
    expect(actual.get(FRONTEND_INSTRUCTIONS)).not.toContain('**Applies to:**');
  });

  it('excludes rules that target other tools', async () => {
    const actual = await renderFixture('copilot', copilot);
    for (const contents of actual.values()) {
      expect(contents).not.toContain('This rule must not reach copilot');
    }
  });

  it('records which rules produced each file', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const artifacts = await copilot.write(ctx);
    const provenance = new Map(artifacts.map((a) => [a.path, a.provenance?.ruleIds]));

    expect(provenance.get(REPO_INSTRUCTIONS)).toEqual(['10-style', '20-testing']);
    expect(provenance.get(FRONTEND_INSTRUCTIONS)).toEqual(['30-frontend']);
  });

  it('emits no file when no rule targets this tool', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = { ...ctx.canonical, rules: [] };
    expect(await copilot.write({ ...ctx, canonical })).toEqual([]);
  });

  it('omits the repo-wide file when every rule is glob-scoped', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [
        rule({
          id: 'scoped',
          frontmatter: { globs: ['src/**'], tools: ALL_TOOLS, order: 100, unknown: {} },
        }),
      ],
    };
    const artifacts = await copilot.write({ ...ctx, canonical });
    expect(artifacts.map((a) => a.path)).toEqual([`${INSTRUCTIONS_DIR}/scoped.instructions.md`]);
  });

  it('refuses to overwrite a generated path that is the canonical source', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = {
      ...ctx.canonical,
      manifest: { ...ctx.canonical.manifest, canonicalSources: [REPO_INSTRUCTIONS] },
    };
    const artifacts = await copilot.write({ ...ctx, canonical });
    expect(artifacts.map((a) => a.path)).toEqual([FRONTEND_INSTRUCTIONS]);
  });

  it('omits the marker when the manifest disables it', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = {
      ...ctx.canonical,
      manifest: {
        ...ctx.canonical.manifest,
        options: { ...ctx.canonical.manifest.options, marker: false },
      },
    };
    const artifacts = await copilot.write({ ...ctx, canonical });
    const byPath = new Map(artifacts.map((a) => [a.path, a.contents]));

    expect(byPath.get(REPO_INSTRUCTIONS)?.startsWith('## Style')).toBe(true);
    expect(byPath.get(FRONTEND_INSTRUCTIONS)).not.toContain('generated by rulegate');
  });

  it('keeps the canonical rule order regardless of how rules arrive', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const reversed: Canonical = { ...ctx.canonical, rules: [...ctx.canonical.rules].reverse() };
    const forward = await copilot.write(ctx);
    const backward = await copilot.write({ ...ctx, canonical: reversed });

    expect(backward.map((a) => [a.path, a.contents])).toEqual(
      forward.map((a) => [a.path, a.contents]),
    );
  });

  it('refuses two rule ids that flatten to one instructions filename', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const scoped = { globs: ['src/**'], tools: ALL_TOOLS, order: 100, unknown: {} };
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [rule({ id: 'a/b', frontmatter: scoped }), rule({ id: 'a-b', frontmatter: scoped })],
    };

    // Silently dropping one rule's content is the failure a flat output directory invites.
    await expect(copilot.write({ ...ctx, canonical })).rejects.toSatisfy(
      (e: unknown) => isRulegateError(e) && e.code === 'E_ARTIFACT_PATH_CONFLICT',
    );
  });

  it('refuses a glob containing the applyTo separator', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [
        rule({
          id: 'commas',
          frontmatter: { globs: ['src/{a,b}/**'], tools: ALL_TOOLS, order: 100, unknown: {} },
        }),
      ],
    };

    // A comma inside applyTo separates patterns, so this glob would silently become two
    // wrong ones. Cursor's .mdc renderer makes the same call for the same reason.
    await expect(copilot.write({ ...ctx, canonical })).rejects.toSatisfy(
      (e: unknown) => isRulegateError(e) && e.code === 'E_FRONTMATTER_INVALID',
    );
  });

  it('folds a multi-line description into the single-line frontmatter scalar', async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [
        rule({
          id: 'wrapped',
          frontmatter: {
            description: 'First line\nsecond line',
            globs: ['src/**'],
            tools: ALL_TOOLS,
            order: 100,
            unknown: {},
          },
        }),
      ],
    };
    const [artifact] = await copilot.write({ ...ctx, canonical });
    expect(artifact?.contents).toContain("description: 'First line second line'");
  });

  it("escapes a quote in a frontmatter value the way YAML's single-quoted style requires", async () => {
    const ctx = await contextFor('copilot/input', copilot);
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [
        rule({
          id: 'quoted',
          frontmatter: {
            description: "Don't break",
            globs: ['src/**'],
            tools: ALL_TOOLS,
            order: 100,
            unknown: {},
          },
        }),
      ],
    };
    const [artifact] = await copilot.write({ ...ctx, canonical });
    expect(artifact?.contents).toContain("description: 'Don''t break'");
  });
});
