import { describe, expect, it } from 'vitest';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@driftgate/adapter-kit/testing';
import { ALL_TOOLS, type Canonical, type RuleDocument } from '@driftgate/adapter-kit';
import { cursor, LEGACY_FILE, RULES_DIR } from '../src/index.js';

function ruleWith(partial: Partial<RuleDocument['frontmatter']> & { id?: string }): RuleDocument {
  const { id = 'r', ...frontmatter } = partial;
  return {
    id,
    path: `.driftgate/rules/${id}.md`,
    body: 'Body.\n',
    frontmatter: { globs: [], tools: ALL_TOOLS, order: 100, unknown: {}, ...frontmatter },
    source: { file: `.driftgate/rules/${id}.md` },
  };
}

describe('cursor write()', () => {
  it('matches the golden .mdc fixture byte for byte', async () => {
    await expectFixtureMatch('cursor', cursor);
  });

  it('writes the legacy file only when the option asks for it', async () => {
    await expectFixtureMatch('cursor-legacy', cursor);

    const withoutLegacy = await renderFixture('cursor', cursor);
    expect(withoutLegacy.has(LEGACY_FILE)).toBe(false);

    const withLegacy = await renderFixture('cursor-legacy', cursor);
    expect(withLegacy.has(LEGACY_FILE)).toBe(true);
  });

  it('writes one file per rule rather than one concatenated file', async () => {
    const actual = await renderFixture('cursor', cursor);
    expect([...actual.keys()].sort()).toEqual([
      `${RULES_DIR}/10-style.mdc`,
      `${RULES_DIR}/20-testing.mdc`,
      `${RULES_DIR}/30-frontend.mdc`,
      `${RULES_DIR}/40-cursor-only.mdc`,
    ]);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent('cursor', cursor);
  });
});

describe('the .mdc frontmatter dialect', () => {
  const render = async (rule: RuleDocument): Promise<string> => {
    const ctx = await contextFor('cursor/input', cursor);
    const canonical: Canonical = { ...ctx.canonical, rules: [rule] };
    const [artifact] = await cursor.write({ ...ctx, canonical });
    return artifact!.contents;
  };

  it('joins globs with commas, unquoted and without a YAML sequence', async () => {
    const out = await render(ruleWith({ globs: ['src/**/*.ts', 'test/**/*.ts'] }));
    // A YAML emitter would write a block sequence or quote this. Cursor expects neither.
    expect(out).toContain('globs: src/**/*.ts,test/**/*.ts');
    expect(out).not.toContain("- 'src/**/*.ts'");
  });

  it('writes an empty globs as a bare key, not as []', async () => {
    const out = await render(ruleWith({ globs: [] }));
    expect(out).toContain('\nglobs:\nalwaysApply: true');
    expect(out).not.toContain('globs: []');
  });

  it('derives alwaysApply from whether the rule is repo-wide', async () => {
    expect(await render(ruleWith({ globs: [] }))).toContain('alwaysApply: true');
    expect(await render(ruleWith({ globs: ['src/**'] }))).toContain('alwaysApply: false');
  });

  it('puts the frontmatter in the first bytes and the marker after it', async () => {
    const out = await render(ruleWith({ description: 'Style' }));
    expect(out.startsWith('---\ndescription: Style\n')).toBe(true);
    const fenceEnd = out.indexOf('\n---\n');
    expect(out.indexOf('<!-- generated by driftgate')).toBeGreaterThan(fenceEnd);
  });

  it('omits description entirely when the rule has none', async () => {
    const out = await render(ruleWith({}));
    expect(out.startsWith('---\nglobs:\n')).toBe(true);
  });

  it('does not add the prose Applies-to line, since Cursor scopes natively', async () => {
    const out = await render(ruleWith({ globs: ['src/**'] }));
    expect(out).not.toContain('Applies to');
  });

  it('rejects a multi-line description rather than corrupting the frontmatter', async () => {
    // The dialect has no escaping: a stray newline would swallow every key after it.
    await expect(render(ruleWith({ description: 'One\nTwo' }))).rejects.toThrow(
      /multi-line description/,
    );
  });

  it('rejects a glob containing a comma, which is the separator', async () => {
    await expect(render(ruleWith({ globs: ['src/{a,b}/**'] }))).rejects.toThrow(/contains a comma/);
  });
});

describe('filename slugs', () => {
  it('refuses to let two rules claim one output file', async () => {
    const ctx = await contextFor('cursor/input', cursor);
    const canonical: Canonical = {
      ...ctx.canonical,
      rules: [ruleWith({ id: 'a/style' }), ruleWith({ id: 'a-style' })],
    };

    await expect(cursor.write({ ...ctx, canonical })).rejects.toThrow(/both generate/);
  });

  it('flattens nested ids into the single rules directory', async () => {
    const ctx = await contextFor('cursor/input', cursor);
    const canonical: Canonical = { ...ctx.canonical, rules: [ruleWith({ id: 'frontend/react' })] };
    const [artifact] = await cursor.write({ ...ctx, canonical });

    expect(artifact?.path).toBe(`${RULES_DIR}/frontend-react.mdc`);
  });
});
