import type { AdapterDocs, SourceLink } from '@driftgate/adapter-kit';

const CODEX_AGENTS_DOCS: SourceLink = {
  url: 'https://developers.openai.com/codex/guides/agents-md',
  title: 'Codex — Custom instructions with AGENTS.md',
  retrieved: '2026-09-02',
};

const CODEX_MCP_DOCS: SourceLink = {
  url: 'https://learn.chatgpt.com/docs/extend/mcp',
  title: 'Codex — Extend with MCP servers',
  retrieved: '2026-09-04',
};

const CODEX_CONFIG_REFERENCE: SourceLink = {
  url: 'https://learn.chatgpt.com/docs/config-file/config-reference',
  title: 'Codex — Config reference',
  retrieved: '2026-09-04',
};

const AGENTS_MD_SPEC: SourceLink = {
  url: 'https://agents.md/',
  title: 'AGENTS.md — a simple, open format for guiding coding agents',
  retrieved: '2026-09-02',
};

/**
 * Encoded precedence knowledge for the Codex CLI.
 *
 * `files` is highest-precedence-first, and for Codex that is the *reverse* of the order
 * the files are concatenated in: Codex joins them from the git root downwards, and a file
 * appearing later in the combined prompt is the one that wins. So the nearest file ranks
 * first here even though it is appended last.
 */
export const docs: AdapterDocs = {
  toolName: 'Codex CLI',
  homepage: 'https://developers.openai.com/codex',
  verifiedAgainst: { version: 'CLI docs as published 2026-09-02', date: '2026-09-02' },
  // Codex concatenates every AGENTS.md from the root down, so a later file wins a conflict while the earlier ones are still loaded.
  resolution: 'additive',
  files: [
    {
      pattern: 'AGENTS.override.md',
      scope: 'nested',
      role: 'instructions',
      managed: false,
      nesting: 'nearest-wins',
      description:
        'Checked before AGENTS.md at every level from the git root down. Never generated by Driftgate: its purpose is to override the shared file, so writing it would defeat it.',
      source: CODEX_AGENTS_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      nesting: 'nearest-wins',
      description:
        'The file Driftgate generates. Codex walks from the git root to the working directory collecting one of these per level and concatenates them, so a nested AGENTS.md adds to the root file rather than replacing it — and, being later in the prompt, wins where they conflict.',
      source: CODEX_AGENTS_DOCS,
    },
    {
      pattern: '~/.codex/AGENTS.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level instructions applied to every project, read before any repository file. Read-only context for `doctor`: Driftgate never writes outside the repository.',
      source: CODEX_AGENTS_DOCS,
    },
    {
      pattern: '.codex/config.toml',
      scope: 'project',
      role: 'mcp',
      managed: true,
      description:
        'Project-level Codex settings, loaded only for a project the user has trusted. Driftgate generates this file from `.driftgate/mcp/servers.yaml` and owns it in full — unlike the other MCP targets, it is not an MCP-only file.',
      source: CODEX_CONFIG_REFERENCE,
    },
    {
      pattern: '~/.codex/config.toml',
      scope: 'global',
      role: 'settings',
      managed: false,
      description:
        'Codex settings. Two keys change what this adapter’s output means: `project_doc_max_bytes` (32 KiB default) caps the combined instruction text, and `project_doc_fallback_filenames` adds further filenames Codex will accept in place of AGENTS.md.',
      source: CODEX_AGENTS_DOCS,
    },
  ],
  limits: {
    maxTotalBytes: 32 * 1024,
    note: 'Codex stops adding instruction files once the concatenated text reaches `project_doc_max_bytes`, 32 KiB by default. Files are added root-first, so it is the nearest — most specific — file that gets dropped when the budget runs out.',
  },
  notes: [
    {
      level: 'warn',
      message:
        'A server Codex cannot express is omitted from .codex/config.toml and named in it as a `# omitted:` comment, rather than failing the run (T083). Codex resolves environment references only through env_vars (which needs the variable and the key to share a name) and bearer_token_env_var (Authorization only), so a renamed reference or a credential in another header has nowhere to go. Check the top of the generated file if a server you configured is missing.',
      source: CODEX_MCP_DOCS,
    },
    {
      level: 'warn',
      message:
        'Driftgate owns the whole of `.codex/config.toml`, not just its `[mcp_servers.*]` tables — it is where every Codex setting lives, and there is no way to write part of a file. A pre-existing one is somebody else’s and is refused until `--force` backs it up; a setting added by hand afterwards is reported as a hand-edit that `sync --import` can recover.',
      source: CODEX_CONFIG_REFERENCE,
    },
    {
      level: 'warn',
      message:
        'Codex has no variable substitution anywhere in config.toml, so an `env:NAME` reference cannot be written as a value the way `${NAME}` and `${env:NAME}` are elsewhere — it has to become a different key. `env: { NAME: env:NAME }` becomes `env_vars = ["NAME"]`, and an Authorization header becomes `bearer_token_env_var`. A reference those two keys cannot express — a renamed variable, or any other header — is refused rather than dropped: a credential that never arrives is a server that starts and fails to authenticate.',
      source: CODEX_MCP_DOCS,
    },
    {
      level: 'warn',
      message:
        'Codex documents streamable HTTP only, with no discriminator for SSE, so a canonical `transport: sse` renders as a bare `url` and the distinction is lost. Lossy but still a working server — the same treatment Cursor’s missing `type` key gets, and the reason it is recorded here rather than left for a user to find.',
      source: CODEX_MCP_DOCS,
    },
    {
      level: 'warn',
      message:
        'AGENTS.md is both a canonical *input* Driftgate accepts and this adapter’s *output*. When a repository has no `.driftgate/` and is using AGENTS.md as its canonical source, this adapter emits nothing rather than generating the file from itself.',
      source: AGENTS_MD_SPEC,
    },
    {
      level: 'info',
      message:
        'AGENTS.md is a cross-vendor format, not a Codex format: VS Code, Cursor, Copilot, Jules, Zed and others read it too. Enabling this adapter alongside claude-code or gemini therefore hands some tools the same rules twice, from two files. That is not an error, but it is worth knowing before it shows up as a doubled token count.',
      source: AGENTS_MD_SPEC,
    },
    {
      level: 'info',
      message:
        'Codex has no per-glob rule mechanism, so a glob-scoped canonical rule is rendered with an "Applies to:" line stating its scope in prose. Lossy, but visibly so; dropping the scope silently would turn a component-only rule into a repo-wide one.',
    },
  ],
};
