import type { AdapterDocs, SourceLink } from '@driftgate/adapter-kit';

const CODEX_AGENTS_DOCS: SourceLink = {
  url: 'https://developers.openai.com/codex/guides/agents-md',
  title: 'Codex — Custom instructions with AGENTS.md',
  retrieved: '2026-09-02',
};

const AGENTS_MD_SPEC: SourceLink = {
  url: 'https://agents.md/',
  title: 'AGENTS.md — a simple, open format for guiding coding agents',
  retrieved: '2026-09-02',
};

/**
 * Encoded precedence knowledge for the Codex CLI.
 *
 * `files` is highest-precedence-first, and for Codex that is the *reverse* of the order
 * the files are concatenated in: Codex joins them from the git root downwards, and a file
 * appearing later in the combined prompt is the one that wins. So the nearest file ranks
 * first here even though it is appended last.
 */
export const docs: AdapterDocs = {
  toolName: 'Codex CLI',
  homepage: 'https://developers.openai.com/codex',
  verifiedAgainst: { version: 'CLI docs as published 2026-09-02', date: '2026-09-02' },
  // Codex concatenates every AGENTS.md from the root down, so a later file wins a conflict while the earlier ones are still loaded.
  resolution: 'additive',
  files: [
    {
      pattern: 'AGENTS.override.md',
      scope: 'nested',
      role: 'instructions',
      managed: false,
      nesting: 'nearest-wins',
      description:
        'Checked before AGENTS.md at every level from the git root down. Never generated by Driftgate: its purpose is to override the shared file, so writing it would defeat it.',
      source: CODEX_AGENTS_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      nesting: 'nearest-wins',
      description:
        'The file Driftgate generates. Codex walks from the git root to the working directory collecting one of these per level and concatenates them, so a nested AGENTS.md adds to the root file rather than replacing it — and, being later in the prompt, wins where they conflict.',
      source: CODEX_AGENTS_DOCS,
    },
    {
      pattern: '~/.codex/AGENTS.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level instructions applied to every project, read before any repository file. Read-only context for `doctor`: Driftgate never writes outside the repository.',
      source: CODEX_AGENTS_DOCS,
    },
    {
      pattern: '~/.codex/config.toml',
      scope: 'global',
      role: 'settings',
      managed: false,
      description:
        'Codex settings. Two keys change what this adapter’s output means: `project_doc_max_bytes` (32 KiB default) caps the combined instruction text, and `project_doc_fallback_filenames` adds further filenames Codex will accept in place of AGENTS.md.',
      source: CODEX_AGENTS_DOCS,
    },
  ],
  limits: {
    maxTotalBytes: 32 * 1024,
    note: 'Codex stops adding instruction files once the concatenated text reaches `project_doc_max_bytes`, 32 KiB by default. Files are added root-first, so it is the nearest — most specific — file that gets dropped when the budget runs out.',
  },
  notes: [
    {
      level: 'warn',
      message:
        'AGENTS.md is both a canonical *input* Driftgate accepts and this adapter’s *output*. When a repository has no `.driftgate/` and is using AGENTS.md as its canonical source, this adapter emits nothing rather than generating the file from itself.',
      source: AGENTS_MD_SPEC,
    },
    {
      level: 'info',
      message:
        'AGENTS.md is a cross-vendor format, not a Codex format: VS Code, Cursor, Copilot, Jules, Zed and others read it too. Enabling this adapter alongside claude-code or gemini therefore hands some tools the same rules twice, from two files. That is not an error, but it is worth knowing before it shows up as a doubled token count.',
      source: AGENTS_MD_SPEC,
    },
    {
      level: 'info',
      message:
        'Codex has no per-glob rule mechanism, so a glob-scoped canonical rule is rendered with an "Applies to:" line stating its scope in prose. Lossy, but visibly so; dropping the scope silently would turn a component-only rule into a repo-wide one.',
    },
  ],
};
