import { describe, expect, it } from 'vitest';
import { DriftgateError, envRef, type Canonical, type McpServer } from '@driftgate/adapter-kit';
import { codex, MCP_FILE, renderConfigToml } from '../src/index.js';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@driftgate/adapter-kit/testing';

const FIXTURE = 'codex-mcp';

async function render(mutate: (c: Canonical) => Canonical = (c) => c): Promise<string | undefined> {
  const ctx = await contextFor(`${FIXTURE}/input`, codex);
  const artifacts = await codex.write({ ...ctx, canonical: mutate(ctx.canonical) });
  return artifacts.find((a) => a.path === MCP_FILE)?.contents;
}

async function servers(): Promise<readonly McpServer[]> {
  return (await contextFor(`${FIXTURE}/input`, codex)).canonical.mcpServers;
}

function serverAt(list: readonly McpServer[], id: string): McpServer {
  const found = list.find((s) => s.id === id);
  if (found === undefined) throw new Error(`fixture has no server \`${id}\``);
  return found;
}

describe('codex MCP output (T047)', () => {
  it('matches the hand-written golden byte for byte', async () => {
    await expectFixtureMatch(FIXTURE, codex);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent(FIXTURE, codex);
  });

  it('generates MCP for a repository with servers and no rules', async () => {
    const actual = await renderFixture(FIXTURE, codex);
    expect([...actual.keys()]).toEqual([MCP_FILE]);
  });

  it('renders the artifact as kind `mcp` with no provenance', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, codex);
    const artifact = (await codex.write(ctx)).find((a) => a.path === MCP_FILE);

    expect(artifact?.kind).toBe('mcp');
    expect(artifact?.provenance).toBeUndefined();
  });

  it('skips a server scoped to another tool, a disabled one and a global one', async () => {
    const contents = (await render()) ?? '';
    expect(contents).not.toContain('cursor-only');
    expect(contents).not.toContain('disabled-server');
    expect(contents).not.toContain('user-global');
  });

  it('writes the tables in id order, which for TOML is the file order', async () => {
    const contents = (await render()) ?? '';
    const headers = [...contents.matchAll(/^\[mcp_servers\.(.+)\]$/gm)].map((m) => m[1]);
    expect(headers).toEqual(['alpha-http', 'linear-sse', 'zebra-stdio']);
  });

  it('writes one order whatever order the servers arrive in', async () => {
    // **The golden cannot see `selectMcpServers`' sort, and T046 predicted that it could.**
    // Its note said TOML would be the first target where insertion order is file order and
    // a fixture would therefore guard the sort. It is not: `parseMcpServers` already sorts
    // by id at parse time, so a fixture's servers reach the adapter sorted however the
    // YAML was written, and deleting the sort passes all 46 tests here. That is the
    // twenty-second inert guard's shape exactly — a normalization elsewhere in the pipeline
    // satisfying the assertion — arriving this time from *upstream* rather than downstream.
    //
    // So the sort's guards are this test and the one in `core/test/mcp.test.ts`, both of
    // which reverse the input by hand. It is still load-bearing: `selectMcpServers` is
    // public API in the frozen kit, and a caller that builds servers programmatically
    // rather than parsing them — T048's importer, an external adapter — gets whatever
    // order it built.
    const list = await servers();
    const reversed: readonly McpServer[] = [...list].reverse();
    expect(renderConfigToml(reversed, true)).toBe(renderConfigToml(list, true));
    expect(renderConfigToml(reversed, true)).toContain(
      '[mcp_servers.alpha-http]\nbearer_token_env_var',
    );
  });

  it('carries a `#` comment marker, not an HTML one', async () => {
    // `withHashMarker` was written at T005 and had no call site for every task since; the
    // note in T005 earmarked it for exactly this file.
    const contents = (await render()) ?? '';
    expect(contents.startsWith('# generated by driftgate; edit .driftgate/ instead\n')).toBe(true);
    expect(contents).not.toContain('<!--');
  });

  it('omits the marker when the manifest disables it', async () => {
    const contents =
      (await render((c) => ({
        ...c,
        manifest: { ...c.manifest, options: { ...c.manifest.options, marker: false } },
      }))) ?? '';
    expect(contents).not.toContain('generated by driftgate');
    expect(contents.startsWith('[mcp_servers.alpha-http]')).toBe(true);
  });

  it('maps a same-named env reference onto `env_vars`, never a value', async () => {
    // Codex has no variable substitution at all, so the reference cannot be a value. It
    // becomes a different key with different semantics: whitelist the name for forwarding.
    const contents = (await render()) ?? '';
    expect(contents).toContain('env_vars = ["GITHUB_TOKEN"]');
    expect(contents).not.toContain('env:GITHUB_TOKEN');
    expect(contents).not.toContain('${');
    expect(contents).not.toContain('[mcp_servers.zebra-stdio.env]');
  });

  it('maps an Authorization header onto `bearer_token_env_var`', async () => {
    const contents = (await render()) ?? '';
    expect(contents).toContain('bearer_token_env_var = "LINEAR_API_KEY"');
    expect(contents).toContain('bearer_token_env_var = "DOCS_API_KEY_PRODUCTION"');
  });

  it('loses the sse distinction, because Codex documents no discriminator', async () => {
    // The documented, deliberate loss: lossy but still a working server, so a `warn` note
    // rather than a refusal — the split Cursor's missing `type` key established.
    const contents = (await render()) ?? '';
    expect(contents).not.toContain('transport');
    expect(contents).not.toContain('type =');
    // The url is all that is left of it, and `sse` survives only as part of that string.
    expect(contents).toContain('url = "https://mcp.linear.app/sse"');
    // So an sse server and an http one differ only in their url and their unknown keys.
    // Asserted so that a `type` key added here later has to change this test deliberately.
    const sse = /\[mcp_servers\.linear-sse\]\n([^[]*)/.exec(contents)?.[1] ?? '';
    expect(
      sse
        .trim()
        .split('\n')
        .map((l) => l.split(' = ')[0]),
    ).toEqual(['bearer_token_env_var', 'url']);
  });

  it('re-emits keys Driftgate does not interpret', async () => {
    // An integer, not a quoted string: TOML has real number syntax and quoting it would
    // change the type Codex reads back.
    expect((await render()) ?? '').toContain('timeout = 600000');
  });

  it('renders nothing when no server targets this tool', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, codex);
    expect(await codex.write({ ...ctx, canonical: { ...ctx.canonical, mcpServers: [] } })).toEqual(
      [],
    );
  });

  it('still refuses to write over a canonical source', async () => {
    const contents = await render((c) => ({
      ...c,
      manifest: { ...c.manifest, canonicalSources: [MCP_FILE] },
    }));
    expect(contents).toBeUndefined();
  });

  it('generates the config even when AGENTS.md is the canonical source', async () => {
    // The sharper half of T046's early-return hole. Using AGENTS.md as canonical is the
    // ordinary way to use Codex, and before T047 that path returned `[]` for the whole
    // adapter — canonical MCP parsed, validated, and silently unreachable.
    const contents = await render((c) => ({
      ...c,
      manifest: { ...c.manifest, canonicalSources: ['AGENTS.md'] },
    }));
    expect(contents).toContain('[mcp_servers.alpha-http]');
  });
});

describe('codex refuses what Codex cannot say (T047)', () => {
  const codeOf = (fn: () => unknown): string | undefined => {
    try {
      fn();
      return undefined;
    } catch (e) {
      return e instanceof DriftgateError ? e.code : `not a DriftgateError: ${String(e)}`;
    }
  };

  it('refuses a renamed environment reference rather than dropping it', async () => {
    const list = await servers();
    const stdio = serverAt(list, 'zebra-stdio');
    const renamed: McpServer = { ...stdio, env: { API_KEY: envRef('MY_TOKEN') } };

    expect(codeOf(() => renderConfigToml([renamed], true))).toBe('E_MCP_UNREPRESENTABLE');
    // The control. An assertion that something throws passes against a function that
    // throws for everything (T020), so the same server with a same-named reference must
    // render — and the message must name the server without quoting anything.
    expect(codeOf(() => renderConfigToml([stdio], true))).toBeUndefined();
    expect(renderConfigToml([stdio], true)).toContain('env_vars = ["GITHUB_TOKEN"]');
  });

  it('refuses an environment reference in a header Codex cannot resolve', async () => {
    const list = await servers();
    const http = serverAt(list, 'alpha-http');
    const other: McpServer = { ...http, headers: { 'X-Api-Key': envRef('DOCS_API_KEY') } };

    expect(codeOf(() => renderConfigToml([other], true))).toBe('E_MCP_UNREPRESENTABLE');
    // Control: Authorization is the one header it can express.
    expect(codeOf(() => renderConfigToml([http], true))).toBeUndefined();
  });

  it('accepts an Authorization header in any casing', async () => {
    const list = await servers();
    const http = serverAt(list, 'alpha-http');
    const lower: McpServer = { ...http, headers: { authorization: envRef('DOCS_API_KEY') } };

    expect(renderConfigToml([lower], false)).toContain('bearer_token_env_var = "DOCS_API_KEY"');
  });

  it('names the server it refused, and never the value', async () => {
    const list = await servers();
    const renamed: McpServer = {
      ...serverAt(list, 'zebra-stdio'),
      env: { API_KEY: envRef('MY_TOKEN') },
    };

    try {
      renderConfigToml([renamed], true);
      expect.unreachable('should have refused');
    } catch (e) {
      const err = e as DriftgateError;
      expect(err.message).toContain('zebra-stdio');
      expect(err.hint).toBeDefined();
      expect(err.source).toBeDefined();
    }
  });
});
