import { cp, mkdir, mkdtemp, readFile, rm, writeFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  applyPlan,
  computePlan,
  findRepoRoot,
  NodeFileSystem,
  serializeState,
  verifyPlan,
  STATE_PATH,
} from '@driftgate/core';
import { ADAPTERS } from '../src/registry.js';
import { runSync } from '../src/commands/sync.js';
import { ExitCode } from '../src/ui/exit.js';

const fixtures = fileURLToPath(new URL('../../../fixtures/', import.meta.url));

let repo: string;

beforeEach(async () => {
  repo = await mkdtemp(path.join(tmpdir(), 'driftgate-'));
  await cp(path.join(fixtures, 'cursor/input'), repo, { recursive: true });
});

afterEach(async () => {
  await rm(repo, { recursive: true, force: true });
});

const planFor = async () =>
  computePlan({ repoRoot: repo, fs: new NodeFileSystem(repo), adapters: ADAPTERS });

const read = (rel: string) => readFile(path.join(repo, rel), 'utf8');

describe('driftgate sync', () => {
  it('generates every enabled tool config from one canonical source', async () => {
    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);

    const claude = await read('CLAUDE.md');
    expect(claude).toContain('<!-- generated by driftgate; edit .driftgate/ instead -->');
    expect(claude).toContain('## Style');
    // The cursor-only rule must not leak into the Claude output.
    expect(claude).not.toContain('composer for multi-file edits');

    const mdc = await read('.cursor/rules/40-cursor-only.mdc');
    expect(mdc).toContain('alwaysApply: true');
    expect(mdc).toContain('Use the composer for multi-file edits.');
  });

  it('records every generated artifact in state.json', async () => {
    await runSync({ cwd: repo, quiet: true });
    const state = JSON.parse(await read(STATE_PATH)) as {
      artifacts: { path: string; adapter: string; hash: string }[];
    };

    expect(state.artifacts.map((a) => a.path)).toEqual([
      '.cursor/rules/10-style.mdc',
      '.cursor/rules/20-testing.mdc',
      '.cursor/rules/30-frontend.mdc',
      '.cursor/rules/40-cursor-only.mdc',
      'CLAUDE.md',
    ]);
    for (const entry of state.artifacts) expect(entry.hash).toMatch(/^sha256:[0-9a-f]{64}$/);
  });

  it('rewrites nothing on a second run', async () => {
    await runSync({ cwd: repo, quiet: true });

    const fs = new NodeFileSystem(repo);
    const spy = vi.spyOn(fs, 'writeFile');
    const report = await applyPlan(await planFor(), fs);

    // Not "writes the same bytes" — writes nothing at all, so mtimes are preserved and
    // file watchers stay quiet.
    expect(spy).not.toHaveBeenCalled();
    expect(report.written).toEqual([]);
    expect(report.unchanged).toHaveLength(5);
    expect(report.stateWritten).toBe(false);
  });

  it('is byte-identical across repeated syncs', async () => {
    await runSync({ cwd: repo, quiet: true });
    const first = await read('CLAUDE.md');
    await runSync({ cwd: repo, quiet: true });
    await runSync({ cwd: repo, quiet: true });
    expect(await read('CLAUDE.md')).toBe(first);
  });

  it('writes nothing at all under --dry-run', async () => {
    const code = await runSync({ cwd: repo, quiet: true, dryRun: true });
    expect(code).toBe(ExitCode.Ok);
    await expect(stat(path.join(repo, 'CLAUDE.md'))).rejects.toThrow();
    await expect(stat(path.join(repo, STATE_PATH))).rejects.toThrow();
  });

  it('refuses to clobber a generated file that was edited by hand', async () => {
    await runSync({ cwd: repo, quiet: true });
    await writeFile(path.join(repo, 'CLAUDE.md'), 'I edited this myself.\n', 'utf8');

    const code = await runSync({ cwd: repo, quiet: true });

    expect(code).toBe(ExitCode.Failure);
    // Losing someone's edit is the one outcome worse than doing nothing.
    expect(await read('CLAUDE.md')).toBe('I edited this myself.\n');
  });

  it('refuses to overwrite a file it never generated', async () => {
    // The first-run case in every real repository: a CLAUDE.md that predates driftgate
    // and is nowhere in state.json. Overwriting it is unrecoverable when, as here, the
    // file is git-ignored.
    const mine = 'My own notes. Driftgate has never seen this file.\n';
    await writeFile(path.join(repo, 'CLAUDE.md'), mine, 'utf8');

    const code = await runSync({ cwd: repo, quiet: true });

    expect(code).toBe(ExitCode.Failure);
    expect(await read('CLAUDE.md')).toBe(mine);
    // Other adapters still run — the refusal is scoped to the one contested path — but
    // state must not claim the file we declined to write.
    const state = JSON.parse(await read(STATE_PATH)) as { artifacts: { path: string }[] };
    expect(state.artifacts.map((a) => a.path)).not.toContain('CLAUDE.md');
  });

  it('never records a file it refused to write as one of its own', async () => {
    // state.json is the only record of what driftgate owns, and orphan deletion (T020)
    // reads it. An entry here for a file we did not write is a future deletion of
    // somebody else's work.
    await writeFile(path.join(repo, 'CLAUDE.md'), 'Mine.\n', 'utf8');
    await runSync({ cwd: repo, quiet: true, force: false });
    await rm(path.join(repo, 'CLAUDE.md'));

    // With the obstacle gone the run succeeds, and only then is CLAUDE.md ours.
    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);
    const state = JSON.parse(await read(STATE_PATH)) as { artifacts: { path: string }[] };
    expect(state.artifacts.map((a) => a.path)).toContain('CLAUDE.md');
  });

  it('under --force, backs the original up byte-exact before taking ownership', async () => {
    const mine = 'My own notes.\r\nWith CRLF endings.\r\n';
    await writeFile(path.join(repo, 'CLAUDE.md'), mine, 'utf8');

    expect(await runSync({ cwd: repo, quiet: true, force: true })).toBe(ExitCode.Ok);

    // Byte-exact, CRLF intact: a backup that rewrites line endings does not restore.
    expect(await read('.driftgate/backup/CLAUDE.md')).toBe(mine);
    expect(await read('CLAUDE.md')).toContain('generated by driftgate');
  });

  it('writes no backup under --force --dry-run', async () => {
    await writeFile(path.join(repo, 'CLAUDE.md'), 'Mine.\n', 'utf8');

    expect(await runSync({ cwd: repo, quiet: true, force: true, dryRun: true })).toBe(ExitCode.Ok);

    expect(await read('CLAUDE.md')).toBe('Mine.\n');
    await expect(stat(path.join(repo, '.driftgate/backup/CLAUDE.md'))).rejects.toThrow();
  });

  it('adopts a pre-existing file whose bytes already match, without --force', async () => {
    await runSync({ cwd: repo, quiet: true });
    const generated = await read('CLAUDE.md');
    await rm(path.join(repo, STATE_PATH));

    // State is gone but the file is exactly what we would render. Refusing here would
    // make a deleted state.json an unrecoverable error rather than an inconvenience.
    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);
    expect(await read('CLAUDE.md')).toBe(generated);
  });

  it('acts on the repository root when run from a subdirectory', async () => {
    // T074. The walk-up chooses the root; writing relative to the subdirectory instead
    // would scatter a second set of configs into every package a developer runs from.
    await mkdir(path.join(repo, 'packages/core'), { recursive: true });

    const root = findRepoRoot(path.join(repo, 'packages/core'));
    expect(await runSync({ cwd: root, quiet: true })).toBe(ExitCode.Ok);

    expect(await read('CLAUDE.md')).toContain('generated by driftgate');
    await expect(stat(path.join(repo, 'packages/core/CLAUDE.md'))).rejects.toThrow();
  });

  it('fails without writing when the canonical source is broken', async () => {
    await writeFile(
      path.join(repo, '.driftgate/rules/10-style.md'),
      '---\norder: high\n---\n\nBody.\n',
      'utf8',
    );

    const code = await runSync({ cwd: repo, quiet: true });

    expect(code).toBe(ExitCode.Failure);
    await expect(stat(path.join(repo, 'CLAUDE.md'))).rejects.toThrow();
  });
});

describe('state.json is regenerable', () => {
  it('comes back byte-identical after being deleted', async () => {
    // T008's stated validation.
    await runSync({ cwd: repo, quiet: true });
    const original = await read(STATE_PATH);

    await rm(path.join(repo, STATE_PATH));
    await runSync({ cwd: repo, quiet: true });

    expect(await read(STATE_PATH)).toBe(original);
  });

  it('survives a corrupt state file without crashing', async () => {
    await runSync({ cwd: repo, quiet: true });
    const original = await read(STATE_PATH);
    await writeFile(path.join(repo, STATE_PATH), '<<<<<<< HEAD\n{ "broken"\n', 'utf8');

    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);
    expect(await read(STATE_PATH)).toBe(original);
  });

  it('matches what the plan said it would be', async () => {
    const plan = await planFor();
    await runSync({ cwd: repo, quiet: true });
    expect(await read(STATE_PATH)).toBe(serializeState(plan.state));
  });
});

describe('check and sync cannot diverge', () => {
  it('verifies clean immediately after a sync', async () => {
    await runSync({ cwd: repo, quiet: true });
    const report = await verifyPlan(await planFor(), new NodeFileSystem(repo));

    expect(report).toEqual({ clean: true, drifted: [], missing: [] });
  });

  it('reports drift when a generated file is edited', async () => {
    await runSync({ cwd: repo, quiet: true });
    await writeFile(path.join(repo, 'CLAUDE.md'), 'drifted\n', 'utf8');

    const report = await verifyPlan(await planFor(), new NodeFileSystem(repo));
    expect(report.clean).toBe(false);
    expect(report.drifted).toEqual(['CLAUDE.md']);
  });

  it('reports drift when a generated file is deleted', async () => {
    await runSync({ cwd: repo, quiet: true });
    await rm(path.join(repo, '.cursor/rules/10-style.mdc'));

    const report = await verifyPlan(await planFor(), new NodeFileSystem(repo));
    expect(report.missing).toEqual(['.cursor/rules/10-style.mdc']);
  });

  it('verifies exactly the bytes sync writes, from one rendering pass', async () => {
    // The structural guarantee: both commands consume the same Plan.artifacts.
    const plan = await planFor();
    await applyPlan(plan, new NodeFileSystem(repo));

    for (const artifact of plan.artifacts) {
      expect(await read(artifact.path)).toBe(artifact.contents);
    }
    expect((await verifyPlan(plan, new NodeFileSystem(repo))).clean).toBe(true);
  });
});

/**
 * T020's deletion half and all of T073.
 *
 * Before this existed, deleting a rule exited 0, printed `wrote CLAUDE.md`, and said
 * nothing about the `.cursor/rules/*.mdc` still on disk — Cursor kept loading a rule the
 * user had deleted, and the tool reported success. Concatenating adapters are immune,
 * which is why the whole class was invisible in this repository's most-watched artifact.
 */
describe('orphaned artifacts (T020 deletion, T073)', () => {
  const rule = (id: string) => path.join(repo, '.driftgate/rules', `${id}.md`);
  const statePaths = async (): Promise<string[]> => {
    const state = JSON.parse(await read(STATE_PATH)) as { artifacts: { path: string }[] };
    return state.artifacts.map((a) => a.path);
  };
  const exists = async (rel: string): Promise<boolean> =>
    await stat(path.join(repo, rel)).then(
      () => true,
      () => false,
    );

  beforeEach(async () => {
    await runSync({ cwd: repo, quiet: true });
  });

  it('deletes the artifact a removed rule used to generate, backing it up first', async () => {
    const before = await read('.cursor/rules/20-testing.mdc');
    await rm(rule('20-testing'));

    const report = await applyPlan(await planFor(), new NodeFileSystem(repo));

    expect(report.deleted).toEqual(['.cursor/rules/20-testing.mdc']);
    expect(await exists('.cursor/rules/20-testing.mdc')).toBe(false);
    // A backup that does not hold the original bytes is not a backup.
    expect(await read('.driftgate/backup/.cursor/rules/20-testing.mdc')).toBe(before);
    // And the record goes with the file: state must describe what is actually there.
    expect(await statePaths()).not.toContain('.cursor/rules/20-testing.mdc');
  });

  it('leaves exactly one artifact per rule after a rename', async () => {
    // Renaming is the obvious way to reorder when filenames carry the order prefix, and
    // it used to leave *both* .mdc files, so Cursor loaded the rule twice.
    await cp(rule('10-style'), rule('15-style'));
    await rm(rule('10-style'));

    await applyPlan(await planFor(), new NodeFileSystem(repo));

    expect(await exists('.cursor/rules/15-style.mdc')).toBe(true);
    expect(await exists('.cursor/rules/10-style.mdc')).toBe(false);
  });

  it('refuses to delete an orphan that was edited after we generated it', async () => {
    await writeFile(path.join(repo, '.cursor/rules/20-testing.mdc'), 'mine now\n', 'utf8');
    await rm(rule('20-testing'));

    const report = await applyPlan(await planFor(), new NodeFileSystem(repo));

    expect(report.deleted).toEqual([]);
    expect(report.skipped).toContainEqual({
      path: '.cursor/rules/20-testing.mdc',
      reason: 'orphan-hand-edited',
    });
    expect(await read('.cursor/rules/20-testing.mdc')).toBe('mine now\n');
  });

  /**
   * T073's second and worse defect, verbatim from its validation.
   *
   * The abandoning run used to *drop* the orphan's state entry, so Driftgate forgot it
   * had written the file. Restoring the rule then made `sync` refuse the path with
   * `1 file driftgate did not generate` — a statement that is simply false about a file
   * Driftgate generated.
   */
  it('keeps a refused orphan in state.json, so restoring its rule is not a false unmanaged claim', async () => {
    const original = await readFile(rule('20-testing'), 'utf8');
    await writeFile(path.join(repo, '.cursor/rules/20-testing.mdc'), 'edited\n', 'utf8');
    await rm(rule('20-testing'));

    await applyPlan(await planFor(), new NodeFileSystem(repo));
    expect(await statePaths()).toContain('.cursor/rules/20-testing.mdc');

    // Put the rule back. The file is now hand-edited, which is a true statement; the one
    // thing it must not be called is a file driftgate did not generate.
    await writeFile(rule('20-testing'), original, 'utf8');
    const report = await applyPlan(await planFor(), new NodeFileSystem(repo));

    const reasons = report.skipped
      .filter((s) => s.path === '.cursor/rules/20-testing.mdc')
      .map((s) => s.reason);
    expect(reasons).toEqual(['hand-edited']);
    expect(reasons).not.toContain('unmanaged');
  });

  it('deletes nothing under --dry-run', async () => {
    await rm(rule('20-testing'));
    const fs = new NodeFileSystem(repo);
    const spy = vi.spyOn(fs, 'deleteFile');

    const report = await applyPlan(await planFor(), fs, { dryRun: true });

    expect(spy).not.toHaveBeenCalled();
    expect(report.deleted).toEqual(['.cursor/rules/20-testing.mdc']);
    expect(await exists('.cursor/rules/20-testing.mdc')).toBe(true);
  });

  it('drops the record for an orphan that is already gone, without trying to delete it', async () => {
    await rm(path.join(repo, '.cursor/rules/20-testing.mdc'));
    await rm(rule('20-testing'));
    const fs = new NodeFileSystem(repo);
    const spy = vi.spyOn(fs, 'deleteFile');

    const report = await applyPlan(await planFor(), fs);

    expect(spy).not.toHaveBeenCalled();
    expect(report.deleted).toEqual([]);
    expect(await statePaths()).not.toContain('.cursor/rules/20-testing.mdc');
  });

  it('honours options.backup: false by deleting without a copy', async () => {
    await writeFile(
      path.join(repo, '.driftgate/driftgate.yaml'),
      'schemaVersion: 1\noptions:\n  backup: false\ntools:\n  - claude-code\n  - cursor\n',
      'utf8',
    );
    await rm(rule('20-testing'));

    const report = await applyPlan(await planFor(), new NodeFileSystem(repo));

    expect(report.deleted).toEqual(['.cursor/rules/20-testing.mdc']);
    expect(report.backedUp).toEqual([]);
    expect(await exists('.driftgate/backup/.cursor/rules/20-testing.mdc')).toBe(false);
  });

  it('reports the deletion rather than exiting 0 in silence', async () => {
    await rm(rule('20-testing'));
    const lines: string[] = [];
    const spy = vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      lines.push(String(chunk));
      return true;
    });

    const code = await runSync({ cwd: repo, color: false });
    spy.mockRestore();

    expect(code).toBe(ExitCode.Ok);
    const output = lines.join('');
    expect(output).toContain('deleted  .cursor/rules/20-testing.mdc');
    expect(output).toContain('backed up  .driftgate/backup/.cursor/rules/20-testing.mdc');
  });
});
