import { cp, mkdtemp, readFile, rm, writeFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  applyPlan,
  computePlan,
  NodeFileSystem,
  serializeState,
  verifyPlan,
  STATE_PATH,
} from '@driftgate/core';
import { ADAPTERS } from '../src/registry.js';
import { runSync } from '../src/commands/sync.js';
import { ExitCode } from '../src/ui/exit.js';

const fixtures = fileURLToPath(new URL('../../../fixtures/', import.meta.url));

let repo: string;

beforeEach(async () => {
  repo = await mkdtemp(path.join(tmpdir(), 'driftgate-'));
  await cp(path.join(fixtures, 'cursor/input'), repo, { recursive: true });
});

afterEach(async () => {
  await rm(repo, { recursive: true, force: true });
});

const planFor = async () =>
  computePlan({ repoRoot: repo, fs: new NodeFileSystem(repo), adapters: ADAPTERS });

const read = (rel: string) => readFile(path.join(repo, rel), 'utf8');

describe('driftgate sync', () => {
  it('generates every enabled tool config from one canonical source', async () => {
    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);

    const claude = await read('CLAUDE.md');
    expect(claude).toContain('<!-- generated by driftgate; edit .driftgate/ instead -->');
    expect(claude).toContain('## Style');
    // The cursor-only rule must not leak into the Claude output.
    expect(claude).not.toContain('composer for multi-file edits');

    const mdc = await read('.cursor/rules/40-cursor-only.mdc');
    expect(mdc).toContain('alwaysApply: true');
    expect(mdc).toContain('Use the composer for multi-file edits.');
  });

  it('records every generated artifact in state.json', async () => {
    await runSync({ cwd: repo, quiet: true });
    const state = JSON.parse(await read(STATE_PATH)) as {
      artifacts: { path: string; adapter: string; hash: string }[];
    };

    expect(state.artifacts.map((a) => a.path)).toEqual([
      '.cursor/rules/10-style.mdc',
      '.cursor/rules/20-testing.mdc',
      '.cursor/rules/30-frontend.mdc',
      '.cursor/rules/40-cursor-only.mdc',
      'CLAUDE.md',
    ]);
    for (const entry of state.artifacts) expect(entry.hash).toMatch(/^sha256:[0-9a-f]{64}$/);
  });

  it('rewrites nothing on a second run', async () => {
    await runSync({ cwd: repo, quiet: true });

    const fs = new NodeFileSystem(repo);
    const spy = vi.spyOn(fs, 'writeFile');
    const report = await applyPlan(await planFor(), fs);

    // Not "writes the same bytes" — writes nothing at all, so mtimes are preserved and
    // file watchers stay quiet.
    expect(spy).not.toHaveBeenCalled();
    expect(report.written).toEqual([]);
    expect(report.unchanged).toHaveLength(5);
    expect(report.stateWritten).toBe(false);
  });

  it('is byte-identical across repeated syncs', async () => {
    await runSync({ cwd: repo, quiet: true });
    const first = await read('CLAUDE.md');
    await runSync({ cwd: repo, quiet: true });
    await runSync({ cwd: repo, quiet: true });
    expect(await read('CLAUDE.md')).toBe(first);
  });

  it('writes nothing at all under --dry-run', async () => {
    const code = await runSync({ cwd: repo, quiet: true, dryRun: true });
    expect(code).toBe(ExitCode.Ok);
    await expect(stat(path.join(repo, 'CLAUDE.md'))).rejects.toThrow();
    await expect(stat(path.join(repo, STATE_PATH))).rejects.toThrow();
  });

  it('refuses to clobber a generated file that was edited by hand', async () => {
    await runSync({ cwd: repo, quiet: true });
    await writeFile(path.join(repo, 'CLAUDE.md'), 'I edited this myself.\n', 'utf8');

    const code = await runSync({ cwd: repo, quiet: true });

    expect(code).toBe(ExitCode.Failure);
    // Losing someone's edit is the one outcome worse than doing nothing.
    expect(await read('CLAUDE.md')).toBe('I edited this myself.\n');
  });

  it('fails without writing when the canonical source is broken', async () => {
    await writeFile(
      path.join(repo, '.driftgate/rules/10-style.md'),
      '---\norder: high\n---\n\nBody.\n',
      'utf8',
    );

    const code = await runSync({ cwd: repo, quiet: true });

    expect(code).toBe(ExitCode.Failure);
    await expect(stat(path.join(repo, 'CLAUDE.md'))).rejects.toThrow();
  });
});

describe('state.json is regenerable', () => {
  it('comes back byte-identical after being deleted', async () => {
    // T008's stated validation.
    await runSync({ cwd: repo, quiet: true });
    const original = await read(STATE_PATH);

    await rm(path.join(repo, STATE_PATH));
    await runSync({ cwd: repo, quiet: true });

    expect(await read(STATE_PATH)).toBe(original);
  });

  it('survives a corrupt state file without crashing', async () => {
    await runSync({ cwd: repo, quiet: true });
    const original = await read(STATE_PATH);
    await writeFile(path.join(repo, STATE_PATH), '<<<<<<< HEAD\n{ "broken"\n', 'utf8');

    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);
    expect(await read(STATE_PATH)).toBe(original);
  });

  it('matches what the plan said it would be', async () => {
    const plan = await planFor();
    await runSync({ cwd: repo, quiet: true });
    expect(await read(STATE_PATH)).toBe(serializeState(plan.state));
  });
});

describe('check and sync cannot diverge', () => {
  it('verifies clean immediately after a sync', async () => {
    await runSync({ cwd: repo, quiet: true });
    const report = await verifyPlan(await planFor(), new NodeFileSystem(repo));

    expect(report).toEqual({ clean: true, drifted: [], missing: [] });
  });

  it('reports drift when a generated file is edited', async () => {
    await runSync({ cwd: repo, quiet: true });
    await writeFile(path.join(repo, 'CLAUDE.md'), 'drifted\n', 'utf8');

    const report = await verifyPlan(await planFor(), new NodeFileSystem(repo));
    expect(report.clean).toBe(false);
    expect(report.drifted).toEqual(['CLAUDE.md']);
  });

  it('reports drift when a generated file is deleted', async () => {
    await runSync({ cwd: repo, quiet: true });
    await rm(path.join(repo, '.cursor/rules/10-style.mdc'));

    const report = await verifyPlan(await planFor(), new NodeFileSystem(repo));
    expect(report.missing).toEqual(['.cursor/rules/10-style.mdc']);
  });

  it('verifies exactly the bytes sync writes, from one rendering pass', async () => {
    // The structural guarantee: both commands consume the same Plan.artifacts.
    const plan = await planFor();
    await applyPlan(plan, new NodeFileSystem(repo));

    for (const artifact of plan.artifacts) {
      expect(await read(artifact.path)).toBe(artifact.contents);
    }
    expect((await verifyPlan(plan, new NodeFileSystem(repo))).clean).toBe(true);
  });
});
