import {
  ADAPTER_API_VERSION,
  DriftgateError,
  detected,
  finalizeArtifact,
  isCanonicalSource,
  renderConcatenated,
  selects,
  sortRules,
  withHtmlMarker,
  type Adapter,
  type AdapterContext,
  type Artifact,
  type Canonical,
  type DetectResult,
  type RuleDocument,
} from '@driftgate/adapter-kit';
import { assertRenderable, frontmatterFor, renderMdcFrontmatter, slugFor } from './mdc.js';
import { docs } from './docs.js';

export const RULES_DIR = '.cursor/rules';
export const LEGACY_FILE = '.cursorrules';

const DETECTION_PATHS = ['.cursor', LEGACY_FILE] as const;

async function detect(ctx: AdapterContext): Promise<DetectResult> {
  const evidence: string[] = [];
  for (const path of DETECTION_PATHS) {
    if (await ctx.fs.exists(path)) evidence.push(path);
  }
  return detected(evidence);
}

async function read(_ctx: AdapterContext): Promise<Partial<Canonical>> {
  return Promise.resolve({}); // Import is T017.
}

function mdcPath(rule: RuleDocument): string {
  return `${RULES_DIR}/${slugFor(rule.id)}.mdc`;
}

function renderMdc(rule: RuleDocument, marker: boolean): string {
  assertRenderable(rule);
  // The marker follows the frontmatter rather than leading the file: .mdc frontmatter
  // must occupy the first bytes, so a leading comment would break parsing.
  const head = renderMdcFrontmatter(frontmatterFor(rule));
  const body = rule.body.replace(/\n+$/, '');
  return marker
    ? `${head}\n<!-- generated by driftgate; edit .driftgate/ instead -->\n\n${body}`
    : `${head}\n${body}`;
}

async function write(ctx: AdapterContext): Promise<readonly Artifact[]> {
  const { canonical } = ctx;
  const marker = canonical.manifest.options.marker;
  const rules = sortRules(canonical.rules.filter((r) => selects(r.frontmatter.tools, 'cursor')));
  if (rules.length === 0) return [];

  const artifacts: Artifact[] = [];
  const claimed = new Map<string, string>();

  for (const rule of rules) {
    const path = mdcPath(rule);

    const previous = claimed.get(path);
    if (previous !== undefined) {
      // Two rule ids slugging to one filename would silently drop one rule's content.
      throw new DriftgateError({
        code: 'E_ARTIFACT_PATH_CONFLICT',
        message: `rules \`${previous}\` and \`${rule.id}\` both generate ${path}`,
        source: rule.source,
        hint: 'rename one of the rules so their generated filenames differ',
      });
    }
    claimed.set(path, rule.id);

    if (isCanonicalSource(canonical.manifest, path)) continue;

    artifacts.push(
      finalizeArtifact({
        path,
        contents: renderMdc(rule, marker),
        adapter: 'cursor',
        kind: 'rules',
        provenance: { ruleIds: [rule.id] },
      }),
    );
  }

  // The legacy single file is opt-in. Writing a deprecated file nobody asked for is
  // exactly the kind of first-run surprise that costs trust.
  if (ctx.options['legacy'] === true && !isCanonicalSource(canonical.manifest, LEGACY_FILE)) {
    artifacts.push(
      finalizeArtifact({
        path: LEGACY_FILE,
        contents: withHtmlMarker(
          renderConcatenated(rules, { headingLevel: 2, showGlobs: true }),
          marker,
        ),
        adapter: 'cursor',
        kind: 'rules',
        provenance: { ruleIds: rules.map((r) => r.id) },
      }),
    );
  }

  return Promise.resolve(artifacts);
}

export const cursor: Adapter = {
  name: 'cursor',
  apiVersion: ADAPTER_API_VERSION,
  detect,
  read,
  write,
  docs,
};

export default cursor;
export { docs, slugFor, renderMdcFrontmatter, frontmatterFor };
